language: R
cache: packages
R: bioc-devel
dist: trusty

os:
  - linux

env:
  - R_BIOC_VERSION: "3.12"

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  

#after_success:
#  - Rscript -e 'pkgdown::build_site()'
#
#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_PAT
#  keep-history: true
#  local-dir: docs
#  on:
#    branch: master