---
title: "Hrvatin et al. Mouse Neuronal Data"
author: "Yingxin Lin"
output:
  html_document:
    theme: flatly
    number_sections: yes
    toc: yes
    fig_height: 8
    fig_width: 8
    toc_float:
      collapsed: true
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r echo = FALSE}
library(ggplot2)
library(ggthemes)
library(scClassify)
library(plotly)
```


# Train Model

```{r}
trainHrvatinresClass <- readRDS("trainHrvatinresClass.rds")
```


```{r}
trainHrvatinresClass
```


Cell type composition:

```{r}
knitr::kable((table(trainHrvatinresClass@cellTypeTrain)), 
             col.names = c("Cell Tpye", "Freq"), align = "c", format = "markdown")
```



# Visualisation

## tSNE
```{r fig.height = 6, fig.width = 9}

g <- ggplot(data.frame(trainHrvatinresClass@metaData), 
       aes(x = tSNE1, y = tSNE2, color = trainHrvatinresClass@cellTypeTrain)) +
  geom_point() +
  scale_colour_tableau(palette = "Tableau 20") +
  theme_bw() +
  theme(legend.position = "bottom",
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA, 
                                    size = 1.2)) +
  labs(title = "Hrvatin et al. (2018)")
ggplotly(g)
```


## Cell Type Tree

```{r}
plotCellTypeTree(trainHrvatinresClass@cellTypeTree, group_level = 4)
```

## Reference

Hrvatin, S. et al., 2018. Single-cell analysis of experience-dependent transcriptomic states in the mouse visual cortex. Nature Neuroscience, 21(1), pp.120–129. Available at: https://doi.org/10.1038/s41593-017-0029-5.
